name: waka ReadMe

on:
  workflow_dispatch:
  schedule:
    # 한국시간으로 수정했음 (UTC+9)
    - cron: '0 15 * * *'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_SHORT_INFO: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_LINES_OF_CODE: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_OS: "True"
          SHOW_PROJECTS: "False"
          SHOW_COMMIT: "True"
          SHOW_LANGUAGE: "True"
          SHOW_EDITORS: "True"
          SHOW_TIMEZONE: "True"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_LOC_CHART: "False"
          SHOW_UPDATED_DATE: "True"
          UPDATED_DATE_FORMAT: "%A, %B %d, %Y"
